# Generated by Django 4.2.4 on 2023-08-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user_choice',
            new_name='priority',
        ),
        migrations.AddField(
            model_name='task',
            name='due_time',
            field=models.TimeField(default='15:14:23'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
