# Generated by Django 4.2.4 on 2023-08-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_user_choice_task_priority_task_due_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default='12-12-2024'),
        ),
    ]
