# Generated by Django 4.2.4 on 2023-08-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('completed', 'completed'), ('expired', 'expired')], default='active', max_length=15),
        ),
    ]
